name: CD
on:
  workflow_run:
    workflows: ["Build and Push Docker Image to GHCR"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Debug workflow run info
        run: |
          echo "Workflow name: ${{ github.event.workflow_run.name }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Current ref: ${{ github.ref_name }}"